# Generated by Django 5.0.7 on 2024-07-14 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name": "Language", "verbose_name_plural": "Language"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student.department",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User_id",
            ),
        ),
    ]
